---
linters-settings:
  # prevent import of "errors" instead of "github.com/pkg/errors"
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - errors

      # use only forked parser
      - github.com/percona/go-mysql/log/slow

  goimports:
    local-prefixes: github.com/percona/pmm-agent

  lll:
    line-length: 170
    tab-width: 4

  unused:
    check-exported: true

  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - scopelint  # too many false positives
    - gochecknoglobals  # mostly useless

run:
  skip-dirs:
    - agents/mongodb/internal/

issues:
  exclude-use-default: false
  exclude:
    # gas: Duplicated errcheck checks
    - 'G104: Errors unhandled'
