---
linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # we use "github.com/golang/protobuf/proto" for now
      - github.com/gogo/protobuf/proto
      - google.golang.org/protobuf/proto
      # use only forked parser
      - github.com/percona/go-mysql/log/slow
      # use "gopkg.in/yaml.v3" instead
      - gopkg.in/yaml.v2

  goimports:
    local-prefixes: github.com/percona/pmm-agent

  lll:
    line-length: 170
    tab-width: 4

  unused:
    check-exported: true

  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    # keep sorted
    - gochecknoglobals  # mostly useless
    - gomodguard        # we are not using modules
    - ifshort           # false positives: https://github.com/esimonov/ifshort/issues/6, 7
    - nlreturn
    - scopelint         # too many false positives
    - wsl               # too annoying

run:
  skip-dirs:
    - agents/mongodb/internal/

issues:
  exclude-use-default: false
  exclude:
    # gas: Duplicated errcheck checks
    - 'G104: Errors unhandled'
  exclude-rules:
    - path: _test\.go
      linters:
        # keep sorted
        - exhaustivestruct # very annoying
        - funlen           # tests may be long
        - gomnd            # tests are full of magic numbers
        - testpackage      # senseless
        - unused           # very annoying false positive: https://github.com/golangci/golangci-lint/issues/791
