---
# The most valuable linters; they are required to pass for PR to be merged.

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # we use "google.golang.org/protobuf/proto"
      - github.com/golang/protobuf/proto
      - github.com/gogo/protobuf/proto
      # use only forked parser
      - github.com/percona/go-mysql/log/slow
      # use "gopkg.in/yaml.v3" instead
      - gopkg.in/yaml.v2

  goimports:
    local-prefixes: github.com/percona/pmm-agent

  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/percona/pmm-agent) # Groups all local imports.

linters:
  disable-all: true
  enable:
    # keep sorted
    - depguard
    - gci
    - goimports
    - govet
    - ineffassign
    - nolintlint
    - staticcheck

run:
  skip-dirs:
    - agents/mongodb/internal/

issues:
  exclude-use-default: false
