dist: bionic
language: go

services:
  - docker

go:
  - 1.14.x
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

go_import_path: github.com/percona/pmm-agent

# skip non-trunk PMM-XXXX/SAAS-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{3,5}/
    - /^SAAS\-\d{2,5}/

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

env:
  global:
    - CODECOV_ENV=MYSQL_IMAGE,MONGO_IMAGE,POSTGRES_IMAGE,PMM_SERVER_IMAGE
    # REVIEWDOG_GITHUB_API_TOKEN
    - secure: "p8VWWWVKVzMPiLN3SEGYUNaiL9oWg7LNhAU1/+43RMDVC40H8m9rmRdcvUQp3lECEOzchsfsfuqhLu+wh0mT9YXry5165hbyI5r4IMcO/X/qIuy1c7Kg3ysdb22hAUdTKcjBg4Ag5XUtj0Ble6Bt2BMsufE8Rkt1o918uv6ZoW9a7WlO/i7dz4uFSrXmoyrJi1xtX3+/BncjVPmnlg1QurSGi9bKWjzm5/epkddQSvle4fRA5kIel6FHGzsmEVo6wXaFSrdPayNzWOyysi/7oeniHk2SaBEO20ZqjaKqT6qVTWWraBuVqksR1cEzeQhH/0oj+YzdBezZKaLdkoSY+YAwUUOsx8A8vYEIyja++/h9Ol0s7yvnszhRaVeF6ckNvwLj/D1n+s8o0S1uSocZDHzxu8ayvl1SpseX9Q0+uSb1Ul9vZj0ZEe38d+r3oC/1ew4juOz/q2ixpFLrCE70yWpZ5l1MxqkMx95bSF1pYSAQhkQRWtj77ghrbXguaqc1d4yMBEQz1h27Cb3ESl3wgi/wrpM5dZgxnndTuVL0TjfdUHmQWPiUDFmPRAYS90D4mgvD9KzYozoNpwAVTrA/Bdi6EOxAp9JcORZZo9wT4BUrrCgoBt2Bcm/3VU29IhK3Wn60vYjkPGUogXqDjCHEVyInsWgRT2S5GoQisZ0Bqfo="

  matrix:
    # latest upstreams + old PMM Server releases
    - MYSQL_IMAGE=mysql:5.6 MONGO_IMAGE=mongo:3.6 POSTGRES_IMAGE=postgres:10 PMM_SERVER_IMAGE=percona/pmm-server:2.0.0
    - MYSQL_IMAGE=mysql:5.7 MONGO_IMAGE=mongo:4.0 POSTGRES_IMAGE=postgres:11 PMM_SERVER_IMAGE=percona/pmm-server:2.0.1
    - MYSQL_IMAGE=mysql:8.0 MONGO_IMAGE=mongo:4.2 POSTGRES_IMAGE=postgres:12 PMM_SERVER_IMAGE=percona/pmm-server:2.1.0

    # Percona + latest PMM Server release
    - MYSQL_IMAGE=percona:5.6 MONGO_IMAGE=percona/percona-server-mongodb:3.6 PMM_SERVER_IMAGE=percona/pmm-server:2
    - MYSQL_IMAGE=percona:5.7 MONGO_IMAGE=percona/percona-server-mongodb:4.0 PMM_SERVER_IMAGE=percona/pmm-server:2
    - MYSQL_IMAGE=percona:8.0 MONGO_IMAGE=percona/percona-server-mongodb:4.2 PMM_SERVER_IMAGE=percona/pmm-server:2

    # MariaDB (only 3 latest GA versions)
    #   + older supported MongoDB versions
    #   + older supported PostgreSQL versions
    #   + dev-latest PMM Server
    # - MYSQL_IMAGE=mariadb:5.5
    # - MYSQL_IMAGE=mariadb:10.0
    # - MYSQL_IMAGE=mariadb:10.1
    - MYSQL_IMAGE=mariadb:10.2 MONGO_IMAGE=mongo:3.4                          POSTGRES_IMAGE=postgres:9.4 PMM_SERVER_IMAGE=perconalab/pmm-server:dev-latest
    - MYSQL_IMAGE=mariadb:10.3 MONGO_IMAGE=percona/percona-server-mongodb:3.4 POSTGRES_IMAGE=postgres:9.5 PMM_SERVER_IMAGE=perconalab/pmm-server:dev-latest
    - MYSQL_IMAGE=mariadb:10.4                                                POSTGRES_IMAGE=postgres:9.6 PMM_SERVER_IMAGE=perconalab/pmm-server:dev-latest

before_install:
  - env ENV_UP_FLAGS=--detach make env-up

install:
  # ensure that vendor/ is in sync with code and Gopkg.toml/lock
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep check
  # install reviewdog
  - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s

before_script:
  # ensure that generated files are not changed
  - make init
  - make gen
  - make format
  - git status
  - git diff --exit-code
  - make ci-reviewdog

script:
  # for main_test.go
  - make install

  - make test-race
  - make test-cover
  - make test-crosscover

  - make release

  - make check

after_success:
  - curl https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f cover.out -F cover -X fix
  - ./codecov -f crosscover.out -F crosscover -X fix

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: ZQUGHsOF2Wy0ylQaXFJam1DGJrf/Cg0m7leqPUsbpFkkWo/yRFxCFXvQegAIL4dzeNhHSI4SuIopsZ3OCw/UpZFlWKJ4qXWgvEYMtUKng8YkX+m4g31rO94o/G6Npo91eAN2MIJ/KB0B+Xs1iQlhCDllDMsxetjK2d1MuZlo3/Qu+qdoOiUJyRQtPbrGbJkufN1d3WxT/gIXIUDpgwI4qNZEsXXLe9jqtOsHB8ZLkBYGu/uVtr7s6aPi2p3M2n9giNK8MUEgG2fM/ySNnQxP3LB/YDckjq5iZkbCS3jyoxnjOZKTQNLh7t1D5QTeieRsQEWm5Nuj8qyNFt9iy4lvZG+3o+9JMl9ZvJe2t4O8RtgScPBmPoY+1I0dlGiJmFiIqfAxj0lo1iyIpPx8ypxh0YTh0r2b7x/Qut+Bwt5gsc7qDAYlS1wZLVGER7F/qF/mqklfGjbZbgU8gyqrj1boYstpDtRIa/ahrOWt52b3CnINLXituuAikw7mn37yVk6CFZO2Vlee/yM3Xj6DElz/VcYDGHRgPzV4Cmh14XR4GoaPIO4jRW7J6uVFmH9Szhs0fyHJpsI2VX2mmO1ws9HtjHbTcrj9ocR03dgUw4UNmbGHO7WRG0pIcH5qy7X40dWF3fHqoMFJLfmeoH1CYplLGTx4yhdV0DuQpOiL53Y+Gi0=
