---
version: '3'
services:
  test_db:
    image: aleksi/test_db:1.0.0
    container_name: pmm-agent_test_db
    volumes:
      - test_db:/test_db/mysql/world:ro

  mysql:
    image: ${MYSQL_IMAGE:-percona:5.7}
    container_name: pmm-agent_mysql
    command: --sql-mode="ANSI_QUOTES" --performance-schema
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_USER=pmm-agent
      - MYSQL_PASSWORD=pmm-agent-password
    volumes:
      - test_db:/docker-entrypoint-initdb.d/:ro

  mongo:
    image: ${MONGO_IMAGE:-mongo:4.0}
    container_name: pmm-agent_mongo
    command: --profile 2
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root-password

  postgres:
    image: ${POSTGRES_IMAGE:-postgres:11}
    container_name: pmm-agent_postgres
    ports:
      - 127.0.0.1:15432:5432
    environment:
      - POSTGRES_USER=pmm-agent
      - POSTGRES_PASSWORD=pmm-agent-password

volumes:
  test_db:
