---
# docker-compose -f docker-compose.yml -f docker-compose-pg-load.yml up postgres-load
version: '3.7'

services:
  postgres-load:
    image: ${POSTGRES_IMAGE:-perconalab/percona-distribution-postgresql:13.3}
    container_name: pmm-agent-postgres-load
    depends_on:
      - postgres
    command: >
      bash -c "
        PGPASSWORD=pmm-agent-password psql -Upmm-agent --host=pmm-agent_postgres -c 'CREATE DATABASE contrib_regression;'
        PGPASSWORD=pmm-agent-password psql -Upmm-agent --host=pmm-agent_postgres -d contrib_regression -c 'CREATE EXTENSION pg_stat_monitor;'
        while true
        do
          PGPASSWORD=pmm-agent-password psql -Upmm-agent --host=pmm-agent_postgres -d contrib_regression -f /testqueries/pg_stat_monitor_load.sql -o /dev/null
          sleep 30
        done
        tail -f /dev/null
      "
    environment:
      - POSTGRES_USER=pmm-agent
      - POSTGRES_PASSWORD=pmm-agent-password
    volumes:
      - ./testqueries/postgres:/testqueries/

volumes:
  test_db_mysql:
  test_db_postgres:
