---
version: '3'
services:
  test_db:
    image: aleksi/test_db:1.1.0
    container_name: pmm-agent_test_db
    volumes:
      - test_db:/test_db/mysql/world:ro
      - test_db_postgres:/test_db/postgresql/world:ro

  mysql:
    image: ${MYSQL_IMAGE:-percona:5.7}
    container_name: pmm-agent_mysql
    command: >
      --sql-mode="ANSI_QUOTES"
      --performance-schema --innodb_monitor_enable=all
      --slow_query_log --slow_query_log_file=/slowlogs/slow.log --long_query_time=0
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_USER=pmm-agent
      - MYSQL_PASSWORD=pmm-agent-password
    volumes:
      - test_db:/docker-entrypoint-initdb.d/:ro
      - ./testdata/slowlogs:/slowlogs

  mongo:
    image: ${MONGO_IMAGE:-mongo:4.0}
    container_name: pmm-agent_mongo
    command: --profile 2
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root-password

  postgres:
    image: ${POSTGRES_IMAGE:-postgres:11}
    container_name: pmm-agent_postgres
    ports:
      - 127.0.0.1:15432:5432
    environment:
      - POSTGRES_USER=pmm-agent
      - POSTGRES_PASSWORD=pmm-agent-password
    volumes:
      - test_db_postgres:/docker-entrypoint-initdb.d/
      - ./testdata/postgres-docker-entrypoint.d/enable_pg_stat_statements.sh:/docker-entrypoint-initdb.d/enable_pg_stat_statements.sh
      - ./testdata/postgres-docker-entrypoint.d/enable_pg_stat_statements.sql:/docker-entrypoint-initdb.d/enable_pg_stat_statements.sql

volumes:
  test_db:
  test_db_postgres:
