ignored = [
  "gonum.org/v1/plot*"  # backoff_draw.go
]

# tools
required = [
  "github.com/BurntSushi/go-sumtype",
  "github.com/vektra/mockery/cmd/mockery",
  "golang.org/x/perf/cmd/benchstat",
  "golang.org/x/tools/cmd/goimports",
  "gopkg.in/reform.v1/reform",

  # for make gen-init when it is needed
  # "gopkg.in/reform.v1/reform-db",
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[prune.project]]
    name = "github.com/lfittl/pg_query_go"
    non-go = false
    unused-packages = false

# TODO switch to tags before PMM 2.0 release
[[constraint]]
  name = "github.com/percona/pmm"
  branch = "PMM-2.0"

# TODO Remove when v1.1.0 is released.
# https://github.com/AlekSi/pointer/milestone/1
[[constraint]]
  name = "github.com/AlekSi/pointer"
  branch = "develop"

[[constraint]]
  name = "github.com/percona/go-mysql"
  branch = "PMM-2.0"

# TODO Remove when PRs are merged.
# We need https://github.com/percona/percona-toolkit/pull/396
# and https://github.com/percona/percona-toolkit/pull/404.
[[constraint]]
  name = "github.com/percona/percona-toolkit"
  branch = "PMM-4278-official-mongo-driver"

# https://jira.percona.com/browse/PMM-4081
[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  branch = "v2.2.6-no-dots"
  source = "https://github.com/Percona-Lab/kingpin.git"

# We want all PMM components to use the same versions of key dependecies to avoid nasty suprises.

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "=1.3.2"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "=1.22.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "=1.9.3"
