ignored = [
  "gonum.org/v1/plot*"  # backoff_draw.go
]

# tools
required = [
  "github.com/BurntSushi/go-sumtype",
  "github.com/vektra/mockery/cmd/mockery",
  "golang.org/x/perf/cmd/benchstat",
  "golang.org/x/tools/cmd/goimports",
  "gopkg.in/reform.v1/reform",

  # for make gen-init when it is needed
  # "gopkg.in/reform.v1/reform-db",
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[prune.project]]
    name = "github.com/lfittl/pg_query_go"
    non-go = false
    unused-packages = false

# TODO switch to tags before PMM 2.0 release
[[constraint]]
  name = "github.com/percona/pmm"
  # branch = "PMM-2.0"
  branch = "PMM-4594-from-v0-to-v1"

# TODO Remove when v1.1.0 is released.
# https://github.com/AlekSi/pointer/milestone/1
[[constraint]]
  name = "github.com/AlekSi/pointer"
  branch = "develop"

[[constraint]]
  name = "github.com/percona/go-mysql"
  branch = "PMM-2.0"

# https://jira.percona.com/browse/PMM-4081
[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  branch = "v2.2.6-no-dots"
  source = "https://github.com/Percona-Lab/kingpin.git"

[[constraint]]
  name = "github.com/lfittl/pg_query_go"
  branch = "master"
  source = "https://github.com/Percona-Lab/pg_query_go"
