ignored = [
  "gonum.org/v1/plot*"  # backoff_draw.go
]

# tools
required = [
  "github.com/BurntSushi/go-sumtype",
  "github.com/vektra/mockery/cmd/mockery",
  "golang.org/x/perf/cmd/benchstat",
  "golang.org/x/tools/cmd/goimports",
  "gopkg.in/reform.v1/reform",

  # for make gen-init when it is needed
  # "gopkg.in/reform.v1/reform-db",
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[prune.project]]
    name = "github.com/lfittl/pg_query_go"
    non-go = false
    unused-packages = false

[[constraint]]
  name = "github.com/percona/pmm"
  branch = "SAAS-20-query-api"
  # branch = "PMM-2.0"

[[constraint]]
  name = "github.com/percona/go-mysql"
  branch = "PMM-2.0"

# to prevent unexpected downgrades
[[constraint]]
  name = "github.com/percona/exporter_shared"
  version = "0.7.2"

# FIXME remove once https://github.com/percona/percona-toolkit/pull/441 is merged
[[override]]
  name = "github.com/pkg/errors"
  version = "0.9.1"

# what we really need is 3.1.1, but it was pulled off:
# https://jira.percona.com/browse/PT-1797?focusedCommentId=249015&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-249015
# FIXME use version once 3.1.1 or later tag is there
[[constraint]]
  name = "github.com/percona/percona-toolkit"
  # version = "3.1.1"
  branch = "3.0"

# https://jira.percona.com/browse/PMM-4081
[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  branch = "v2.2.6-no-dots"
  source = "https://github.com/Percona-Lab/kingpin.git"

[[constraint]]
  name = "github.com/lfittl/pg_query_go"
  branch = "master"
  source = "https://github.com/Percona-Lab/pg_query_go"
