ignored = [
  "gonum.org/v1/plot*"  # backoff_draw.go
]

# tools
required = [
  # "gopkg.in/reform.v1/reform-db",
  "gopkg.in/reform.v1/reform"
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

# TODO switch to tags before PMM 2.0 release
[[constraint]]
  name = "github.com/percona/pmm"
  # branch = "PMM-2.0"
  branch = "PMM-3707-standard-labels"

[[constraint]]
  # Stick to 0.9.x for now.
  # https://github.com/prometheus/client_golang#important-note-about-releases-versioning-tagging-and-stability
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

# TODO Remove when v1.1.0 is released.
# https://github.com/AlekSi/pointer/milestone/1
[[constraint]]
  name = "github.com/AlekSi/pointer"
  branch = "develop"

[[constraint]]
  name = "github.com/percona/go-mysql"
  branch = "PMM-2.0"
