ignored = [
  "gonum.org/v1/plot*"  # backoff_draw.go
]

# tools
required = [
  "gopkg.in/reform.v1/reform",
  "github.com/BurntSushi/go-sumtype",
  "github.com/vektra/mockery/cmd/mockery",

  # for make gen-init when it is needed
  # "gopkg.in/reform.v1/reform-db",
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

# TODO switch to tags before PMM 2.0 release
[[constraint]]
  name = "github.com/percona/pmm"
  branch = "PMM-3978-actions"

# Stick to 0.9.x for now.
# https://github.com/prometheus/client_golang#important-note-about-releases-versioning-tagging-and-stability
[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

# TODO Remove when v1.1.0 is released.
# https://github.com/AlekSi/pointer/milestone/1
[[constraint]]
  name = "github.com/AlekSi/pointer"
  branch = "develop"

[[constraint]]
  name = "github.com/percona/go-mysql"
  branch = "PMM-2.0"

# TODO Remove when 3.0.14 is released.
# We need https://github.com/percona/percona-toolkit/pull/396.
[[constraint]]
  name = "github.com/percona/percona-toolkit"
  branch = "3.0"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.1.1"
