// Code generated by mockery v1.0.0. DO NOT EDIT.

package agentlocal

import agentpb "github.com/percona/pmm/api/agentpb"
import mock "github.com/stretchr/testify/mock"
import prometheus "github.com/prometheus/client_golang/prometheus"
import shared "github.com/percona/pmm-agent/client/shared"

// mockClient is an autogenerated mock type for the client type
type mockClient struct {
	mock.Mock
}

// Collect provides a mock function with given fields: _a0
func (_m *mockClient) Collect(_a0 chan<- prometheus.Metric) {
	_m.Called(_a0)
}

// Describe provides a mock function with given fields: _a0
func (_m *mockClient) Describe(_a0 chan<- *prometheus.Desc) {
	_m.Called(_a0)
}

// GetAgentServerMetadata provides a mock function with given fields:
func (_m *mockClient) GetAgentServerMetadata() *agentpb.AgentServerMetadata {
	ret := _m.Called()

	var r0 *agentpb.AgentServerMetadata
	if rf, ok := ret.Get(0).(func() *agentpb.AgentServerMetadata); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agentpb.AgentServerMetadata)
		}
	}

	return r0
}

// GetNetworkInformation provides a mock function with given fields:
func (_m *mockClient) GetNetworkInformation() (*shared.NetworkInformation, error) {
	ret := _m.Called()

	var r0 *shared.NetworkInformation
	if rf, ok := ret.Get(0).(func() *shared.NetworkInformation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shared.NetworkInformation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
