// Code generated by mockery v1.0.0. DO NOT EDIT.

package agentlocal

import (
	agentlocalpb "github.com/percona/pmm/api/agentlocalpb"
	mock "github.com/stretchr/testify/mock"
)

// mockRegistry is an autogenerated mock type for the registry type
type mockRegistry struct {
	mock.Mock
}

// TunnelsList provides a mock function with given fields:
func (_m *mockRegistry) TunnelsList() []*agentlocalpb.TunnelInfo {
	ret := _m.Called()

	var r0 []*agentlocalpb.TunnelInfo
	if rf, ok := ret.Get(0).(func() []*agentlocalpb.TunnelInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*agentlocalpb.TunnelInfo)
		}
	}

	return r0
}
